CREATE TABLE user
(
  id                      INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  username                VARCHAR(255)                                                                 DEFAULT '',
  password                VARCHAR(255)                                                                 DEFAULT '',
  role                    VARCHAR(255)                                                                 DEFAULT '',
  account_non_expired     TINYINT                                                             DEFAULT 0 NOT NULL,
  account_non_locked      TINYINT                                                             DEFAULT 0 NOT NULL,
  credentials_non_expired TINYINT                                                             DEFAULT 0 NOT NULL,
  enabled                 TINYINT                                                             DEFAULT 0 NOT NULL,
  create_time             DATETIME                                                                     DEFAULT CURRENT_TIMESTAMP NOT NULL,
  update_time             DATETIME                                                                     DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE process
(
  id                      INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  name                VARCHAR(255)                                                                 DEFAULT '',
  PRIMARY KEY (id)
);

CREATE TABLE sequence_flow
(
  id                      INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  name                VARCHAR(255)                                                                 DEFAULT '',
  process_id                 INT                                                             DEFAULT 0 NOT NULL,
  PRIMARY KEY (id)
);
